root = "."
tmp_dir = "tmp"
build = "go build -o ./tmp/main"
cmd = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules"]
include_dir = []
exclude_file = []
delay = 1000