version: "3.3"
services:

  db:
    image: "postgres:14.2"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account-bank-backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  account-bank-backend-service:
    container_name: account-bank-backend-service
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "4000:8080"
    environment:
      - air_wd=/app
    env_file:
      - ./.env.local
    volumes:
      - ./:/app
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
