FROM golang:1.23.5 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download && \
    go install github.com/air-verse/air@v1.52.2

COPY *.go ./
RUN chmod +x /app

EXPOSE 8080

ENTRYPOINT [ "air" ]